-- AlterTable
ALTER TABLE `factionattack` ADD COLUMN `attackerFactionName` VARCHAR(191) NULL,
    ADD COLUMN `defenderFactionName` VARCHAR(191) NULL,
    ADD COLUMN `modChain` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `modGroup` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `modOverseas` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `modRetaliation` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `modWar` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `modWarlord` DOUBLE NOT NULL DEFAULT 0;
